name: Deploy Github Pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Node.js
        uses: action/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: install deps
        run: npm i -g yarn && yarn
      - name: build
        run: yarn build
      - name: configure pages
        uses: actions/configure-pages@v3
      - name: upload build
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
